using System.IO;
using System.Text;
using HostsGuardian.Core.Models;

namespace HostsGuardian.Core.Services;

public sealed class HostsService
{
    public const string BeginMarker = "# HOSTSGUARDIAN BEGIN";
    public const string EndMarker = "# HOSTSGUARDIAN END";

    public bool IsBlockPresent()
    {
        var text = File.Exists(PathsService.HostsPath) ? File.ReadAllText(PathsService.HostsPath) : "";
        return text.Contains(BeginMarker) && text.Contains(EndMarker);
    }

    public string CreateBackup()
    {
        var ts = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        var backupPath = Path.Combine(PathsService.HostsDir, $"hosts.backup_{ts}");
        File.Copy(PathsService.HostsPath, backupPath, overwrite: false);
        return backupPath;
    }

    public string BuildBlock(IEnumerable<DomainEntry> domains)
    {
        var clean = domains
            .Select(d => NormalizeDomain(d.Domain))
            .Where(d => !string.IsNullOrWhiteSpace(d))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(d => d, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine(BeginMarker);
        sb.AppendLine("# Generated by HostsGuardian");
        sb.AppendLine("# IPv4 + IPv6 loopback entries");

        foreach (var dom in clean)
        {
            sb.AppendLine($"127.0.0.1 {dom}");
            sb.AppendLine($"127.0.0.1 www.{dom}");
            sb.AppendLine($"::1 {dom}");
            sb.AppendLine($"::1 www.{dom}");
        }

        sb.AppendLine(EndMarker);
        return sb.ToString();
    }

    public string PreviewResult(AppConfig cfg)
    {
        var current = File.Exists(PathsService.HostsPath) ? File.ReadAllText(PathsService.HostsPath) : "";
        var stripped = RemoveExistingBlock(current);
        var block = BuildBlock(cfg.BlockedDomains);
        var combined = EnsureEndsWithNewline(stripped) + Environment.NewLine + block + Environment.NewLine;
        return combined;
    }

    public void Apply(AppConfig cfg)
    {
        if (!File.Exists(PathsService.HostsPath))
            throw new FileNotFoundException("Hosts file not found", PathsService.HostsPath);

        CreateBackup();

        var current = File.ReadAllText(PathsService.HostsPath);
        var stripped = RemoveExistingBlock(current);
        var block = BuildBlock(cfg.BlockedDomains);

        var combined = EnsureEndsWithNewline(stripped) + Environment.NewLine + block + Environment.NewLine;
        File.WriteAllText(PathsService.HostsPath, combined, Encoding.UTF8);
    }

    public void Revert()
    {
        if (!File.Exists(PathsService.HostsPath))
            return;

        CreateBackup();

        var current = File.ReadAllText(PathsService.HostsPath);
        var stripped = RemoveExistingBlock(current);
        File.WriteAllText(PathsService.HostsPath, EnsureEndsWithNewline(stripped), Encoding.UTF8);
    }

    private static string RemoveExistingBlock(string text)
    {
        var start = text.IndexOf(BeginMarker, StringComparison.Ordinal);
        var end = text.IndexOf(EndMarker, StringComparison.Ordinal);

        if (start < 0 || end < 0 || end < start)
            return text;

        end += EndMarker.Length;

        var before = text[..start].TrimEnd();
        var after = text[end..].TrimStart();

        if (string.IsNullOrWhiteSpace(before))
            return after;

        if (string.IsNullOrWhiteSpace(after))
            return before + Environment.NewLine;

        return before + Environment.NewLine + Environment.NewLine + after;
    }

    public static string NormalizeDomain(string input)
    {
        var d = (input ?? "").Trim().ToLowerInvariant();

        if (d.StartsWith("http://")) d = d["http://".Length..];
        if (d.StartsWith("https://")) d = d["https://".Length..];
        if (d.StartsWith("www.")) d = d["www.".Length..];

        var slash = d.IndexOf('/');
        if (slash >= 0) d = d[..slash];

        d = d.Trim().Trim('.');
        return d;
    }

    private static string EnsureEndsWithNewline(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        if (s.EndsWith("\r\n") || s.EndsWith("\n")) return s;
        return s + Environment.NewLine;
    }
}
